name = "script"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.68.1 and < 1.0.0"
gleam_hackney = ">= 1.3.3 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
htmerl = ">= 0.2.1 and < 1.0.0"
htmgrrrl = ">= 0.3.0 and < 1.0.0"
envoy = ">= 1.1.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
