# Site settings
title: Perivan
url: http://perivan.lpil.uk
# url: http://www.perivan.co.uk
description: >
  TODO

static: http://perivan.lpil.uk/static

# Contact
email: financial@perivan.co.uk # TODO
telephone: +44 (0)20 7562 2200
fax: +44 (0)20 7562 2201
address1: 21 Worship Street
address2: London
address3: EC2A 2DW

# Build settings
markdown: kramdown
permalink: /news/:title

exclude:
  - dev_serve.sh
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: :compressed
  sass_dir: _scss

gems:
  - jekyll-sitemap
