# Site settings
title: Perivan Financial
url: http://perivanfinancialpod.lpil.uk
# url: http://www.perivanfinancialpod.co.uk
description: >
  We are the print on-demand arm of Perivan Financial, the UKâ€™s leading
  independent financial printer. We are entirely owned and run by people who
  work for the company and our core team is without question the most
  established in the marketplace.

static: http://perivan.lpil.uk/static

# Contact
email: financial@perivan.co.uk
telephone: +44 (0)20 7562 2278
fax: +44 (0)20 7562 2201
address1: 21 Worship Street
address2: London
address3: EC2A 2DW

# Navigation sections
nav-sections:
  - About
  - Resource

# Build settings
markdown: kramdown
permalink: /news/:title

exclude:
  - dev_serve.sh
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: :compressed
  sass_dir: _scss

gems:
  - jekyll-sitemap
