version: 2
jobs:
  build:
    working_directory: ~/particle
    docker:
      - image: bitwalker/alpine-elixir:1.6.3
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: particle_test
    environment:
      - MIX_ENV: test
    steps:
      - checkout
      - run: cp mix.lock mix.lock.bak

      # Restore cache
      - run: apk add --update tar alpine-sdk coreutils curl curl-dev docker make
      - restore_cache:
          key: particle-elixir-{{ checksum "mix.lock.bak" }}

      # Install deps
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

      # Cache deps
      - run: mix clean
      - save_cache:
          key: particle-elixir-{{ checksum "mix.lock.bak" }}
          paths:
            - deps
            - _build

      # Compile
      - run: mix compile --warnings-as-errors

      # Setup database
      - run: mix ecto.setup

      # Test
      - run: mix ecto.seed
      - run: mix test
      - run: mix format --check-formatted

      # TODO: Build and push docker image
      # - setup_remote_docker
      # - run: ./bin/docker-ci-build.sh
